name: CI Builds

on: push

jobs:
  macos:
    name: MacOS
    runs-on: macos-10.15
    env:
      CMAKE_INSTALL_PREFIX: '/opt/smelibs'
      MACOSX_DEPLOYMENT_TARGET: '10.14'
      DUNE_USE_FALLBACK_FILESYSTEM: 'ON'
      TERM: 'xterm-256color'
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Build and Install
        run: brew install --HEAD dune-copasi/tap/dune-copasi@0.3
